apiVersion: v1
kind: Pod
metadata:
  name: consume-via-env
spec:
  containers:
    - name: consuming-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      envFrom:
      - configMapRef:
          name: ucs-info
  restartPolicy: Never
