apiVersion: v1
kind: Pod
metadata:
  name: consume-via-vol
spec:
  containers:
    - name: consuming-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh","-c","cat /etc/config/keys" ]
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: ucs-info
        items:
        - key: ucs-org
          path: keys
  restartPolicy: Never